package com.bll.lnkcommon.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bll.lnkcommon.mvp.model.AppBean;
import com.bll.lnkcommon.mvp.model.Book;
import com.bll.lnkcommon.mvp.model.DateEvent;
import com.bll.lnkcommon.mvp.model.Note;
import com.bll.lnkcommon.mvp.model.NoteContent;
import com.bll.lnkcommon.mvp.model.Notebook;
import com.bll.lnkcommon.mvp.model.RecordBean;

import com.bll.lnkcommon.greendao.AppBeanDao;
import com.bll.lnkcommon.greendao.BookDao;
import com.bll.lnkcommon.greendao.DateEventDao;
import com.bll.lnkcommon.greendao.NoteDao;
import com.bll.lnkcommon.greendao.NoteContentDao;
import com.bll.lnkcommon.greendao.NotebookDao;
import com.bll.lnkcommon.greendao.RecordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appBeanDaoConfig;
    private final DaoConfig bookDaoConfig;
    private final DaoConfig dateEventDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig noteContentDaoConfig;
    private final DaoConfig notebookDaoConfig;
    private final DaoConfig recordBeanDaoConfig;

    private final AppBeanDao appBeanDao;
    private final BookDao bookDao;
    private final DateEventDao dateEventDao;
    private final NoteDao noteDao;
    private final NoteContentDao noteContentDao;
    private final NotebookDao notebookDao;
    private final RecordBeanDao recordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appBeanDaoConfig = daoConfigMap.get(AppBeanDao.class).clone();
        appBeanDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        dateEventDaoConfig = daoConfigMap.get(DateEventDao.class).clone();
        dateEventDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        noteContentDaoConfig = daoConfigMap.get(NoteContentDao.class).clone();
        noteContentDaoConfig.initIdentityScope(type);

        notebookDaoConfig = daoConfigMap.get(NotebookDao.class).clone();
        notebookDaoConfig.initIdentityScope(type);

        recordBeanDaoConfig = daoConfigMap.get(RecordBeanDao.class).clone();
        recordBeanDaoConfig.initIdentityScope(type);

        appBeanDao = new AppBeanDao(appBeanDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);
        dateEventDao = new DateEventDao(dateEventDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        noteContentDao = new NoteContentDao(noteContentDaoConfig, this);
        notebookDao = new NotebookDao(notebookDaoConfig, this);
        recordBeanDao = new RecordBeanDao(recordBeanDaoConfig, this);

        registerDao(AppBean.class, appBeanDao);
        registerDao(Book.class, bookDao);
        registerDao(DateEvent.class, dateEventDao);
        registerDao(Note.class, noteDao);
        registerDao(NoteContent.class, noteContentDao);
        registerDao(Notebook.class, notebookDao);
        registerDao(RecordBean.class, recordBeanDao);
    }
    
    public void clear() {
        appBeanDaoConfig.clearIdentityScope();
        bookDaoConfig.clearIdentityScope();
        dateEventDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        noteContentDaoConfig.clearIdentityScope();
        notebookDaoConfig.clearIdentityScope();
        recordBeanDaoConfig.clearIdentityScope();
    }

    public AppBeanDao getAppBeanDao() {
        return appBeanDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public DateEventDao getDateEventDao() {
        return dateEventDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public NoteContentDao getNoteContentDao() {
        return noteContentDao;
    }

    public NotebookDao getNotebookDao() {
        return notebookDao;
    }

    public RecordBeanDao getRecordBeanDao() {
        return recordBeanDao;
    }

}
