package com.bll.lnkcommon.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import java.util.List;

import com.bll.lnkcommon.mvp.model.FreeNoteBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FREE_NOTE_BEAN".
*/
public class FreeNoteBeanDao extends AbstractDao<FreeNoteBean, Long> {

    public static final String TABLENAME = "FREE_NOTE_BEAN";

    /**
     * Properties of entity FreeNoteBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Date = new Property(3, long.class, "date", false, "DATE");
        public final static Property BgRes = new Property(4, String.class, "bgRes", false, "BG_RES");
        public final static Property Paths = new Property(5, String.class, "paths", false, "PATHS");
    }

    private final StringConverter pathsConverter = new StringConverter();

    public FreeNoteBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FreeNoteBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FREE_NOTE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TITLE\" TEXT," + // 2: title
                "\"DATE\" INTEGER NOT NULL ," + // 3: date
                "\"BG_RES\" TEXT," + // 4: bgRes
                "\"PATHS\" TEXT);"); // 5: paths
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FREE_NOTE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FreeNoteBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getDate());
 
        String bgRes = entity.getBgRes();
        if (bgRes != null) {
            stmt.bindString(5, bgRes);
        }
 
        List paths = entity.getPaths();
        if (paths != null) {
            stmt.bindString(6, pathsConverter.convertToDatabaseValue(paths));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FreeNoteBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getDate());
 
        String bgRes = entity.getBgRes();
        if (bgRes != null) {
            stmt.bindString(5, bgRes);
        }
 
        List paths = entity.getPaths();
        if (paths != null) {
            stmt.bindString(6, pathsConverter.convertToDatabaseValue(paths));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FreeNoteBean readEntity(Cursor cursor, int offset) {
        FreeNoteBean entity = new FreeNoteBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.getLong(offset + 3), // date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bgRes
            cursor.isNull(offset + 5) ? null : pathsConverter.convertToEntityProperty(cursor.getString(offset + 5)) // paths
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FreeNoteBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.getLong(offset + 3));
        entity.setBgRes(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPaths(cursor.isNull(offset + 5) ? null : pathsConverter.convertToEntityProperty(cursor.getString(offset + 5)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FreeNoteBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FreeNoteBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FreeNoteBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
